name: publicar

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set current date as env variable
      id: date
      run: echo "date=$(date +'%Y.%m.%d.%H%M')" >> $GITHUB_OUTPUT
    - name: Echo current date
      run: echo ${{ steps.date.outputs.date }}
    
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies Motor
      run: dotnet restore
      working-directory: 'src/'
      
    - name: Build
      run: dotnet build --no-restore
      working-directory: 'src/'
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: 'src/'
      
    - name: Publish-Nuget
      uses: robertorp/publish-nuget@master
      with:
        PROJECT_FILE_PATH: 'src/MotorTributarioNet/MotorTributarioNet.csproj'
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        TAG_COMMIT: false
        VERSION_STATIC: ${{ steps.date.outputs.date }}
